### PR TITLE
Fixing dependency information

### PR DESCRIPTION
**Pull request by adamw**
* the organization was wrong
* the artifacts aren't available in the central repository, I had to add the bintray repo

### CODE REVIEW

**Comment by ahjohannessen** [comment]
I would like to merge this, but I have no idea which steps are involved generating and publishing docs :/

**Comment by adamw** [comment]
I think if it's automatic, anything in the `gh-pages` branch goes automatically to the `github.io` subpage

**Comment by adamw** [comment]
See here: https://pages.github.com
It should get updated automatically

**Comment by timperrett** [comment]
@ahjohannessen you just need to run `sbt docs/ghpagesPushSite` :-)

**Comment by timperrett** [comment]
Just updated it :-)

**Comment by timperrett** [comment]
Actually, looks like the docs wont build: 

```
[tut] *** Error reported at index.md:109
<console>:17: error: not enough arguments for method specify1: (name: String, in: remotely.Field[Int], out: remotely.Type[Int])(implicit evidenceA: shapeless.ops.hlist.Selector[shapeless.::[Int,shapeless.HNil],Int], implicit evidenceB: shapeless.ops.hlist.Selector[shapeless.::[Int,shapeless.HNil],Int])remotely.Protocol[shapeless.::[Int,shapeless.HNil]].
Unspecified value parameters in, out.
           .specify1[Int, Int]("factorial")
                              ^
```

**Comment by adamw** [comment]
Ah! I see that I created the PR to the wrong branch - didn't know that the docs are generated from master. #99 contains the change in the proper place, plus fixes compilation. There are also some other unsynchronised changes on `master`.

Maybe it would make sense to add a "contributing" section to the docs? I see that I'm not the only one doing PRs straight to the `gh-pages` branch, so maybe it's worth documenting

**Comment by ahjohannessen** [comment]
@timperrett Ah, ok that seems manageable :D

**Comment by ahjohannessen** [comment]
>Maybe it would make sense to add a "contributing" section to the docs?

Great idea :)

**Comment by ahjohannessen** [comment]
>There are also some other unsynchronised changes on master

Yes, I think that the docs could get some attention, a bit outdated/incomplete in some areas.

**Pull request merged**
