### PR TITLE
Add test-server to the aggreagate project file

### PR DESCRIPTION
**Pull request by jedesah**
This is in order to run ALL tests when using the test command in the top-level project

### CODE REVIEW

**Comment by jedesah** [comment]
@stew Here is the code we just looked at. It compiles but there are verbose implicit values that are annoying.

**Comment by jedesah** [comment]
It started out as just adding `test-server` to the master build, but then I realized that the tests in that sub-project were broken (and have been for a while) so I also pilled on the changes to fix these tests.

**Comment by stew** [comment]
@jedesah I sent a PR to this branch, I have run into this problem before. Long story short: "variance can break inference in scala".  Short story long: https://github.com/scodec/scodec/pull/26 and https://issues.scala-lang.org/browse/SI-8877

**Comment by jedesah** [comment]
@stew Thx! I merged the PR and did a little polishing. Would you do the honors?

**Pull request merged**
