### PR TITLE
Performance improvement, moving write and flush out of enframed and i…

### PR DESCRIPTION
**Pull request by sbuzzard**
…nto framed write itself

### CODE REVIEW

**Comment by runarorama** [comment]
Sweet! Any measurement of by how much this improves throughput?

**Comment by sbuzzard** [comment]
Nothing formal; however, the benchmark tests for our application's use of remotely showed significant improvement.  An exercise of 60 concurrent RPC calls (where the payload size varied between ~30 and 1024 bytes) took 1/10th the time to execute.  And a more complete integration test suite of 125 tests that talk to two RPC servers (one handling persistence and one executing downstream messaging to clients) dropped from nearly 3 minutes to less than 30 seconds.

**Comment by ahjohannessen** [comment]
What is the status of this? :) Btw @sbuzzard I have an open PR that bumps netty to 4.1.0

**Comment by sbuzzard** [comment]
@ahjohannessen - Not sure.  We have been working with our own fork and I had forgotten to follow up.  This change has made a *world* of difference in performance with our applications, but I'd definitely like to try with netty 4.1.0.  I'm guessing it hasn't been merged since the travis builds are failing, but I don't think those failures are (at least directly) related to this change ...

**Comment by ahjohannessen** [comment]
@sbuzzard Ok. You are correct with travis failures, they have been happening for a long time now.

**Comment by timperrett** [comment]
@sbuzzard @ahjohannessen sorry for the delay on this - i had not noticed the PR (subsequently fixed my github notification settings). This looks like another great change

**Pull request merged**
