### PR TITLE
build: upgrades

### PR DESCRIPTION
**Pull request by ahjohannessen**
- upgrade scodec to 1.8.1 and thereby shapeless to 2.2.4.

 - upgrade scodec-scalaz to 1.1.0 in order to match
   scodec upgrade.

 - fix `DescribeSpec` wrt. casing error.

 - bump travis jdk version.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@timperrett @stew Could we also get a release if/when this gets in? :)

**Comment by ahjohannessen** [comment]
weird errors coming from travis CI:
```
[error] /home/travis/build/oncue/remotely/examples/src/main/scala/Protocol.scala:25: exception during macro expansion: 
[error] java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets
```
I don't believe that has anything doing with this PR.

**Comment by ahjohannessen** [comment]
Perhaps clearing the cache on travis solves this, see this: http://docs.travis-ci.com/user/caching/#Clearing-Caches

**Comment by timperrett** [comment]
@ahjohannessen this doesnt even compile for me locally. I get the following:

```
[error] /Users/timperrett/sandbox/scala/ahjohannessen-remotely/examples/src/main/scala/Protocol.scala:25: exception during macro expansion:
[error] java.lang.ClassNotFoundException: java.nio.charset.StandardCharsets
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[error] 	at scodec.codecs.package$.<init>(package.scala:452)
[error] 	at scodec.codecs.package$.<clinit>(package.scala)
[error] 	at remotely.codecs.package$.<init>(codecs.scala:48)
[error] 	at remotely.codecs.package$.<clinit>(codecs.scala)
[error] 	at remotely.Codecs$.<init>(Codecs.scala:46)
[error] 	at remotely.Codecs$.<clinit>(Codecs.scala)
[error] 	at remotely.Protocol$.<init>(Protocol.scala:56)
[error] 	at remotely.Protocol$.<clinit>(Protocol.scala)
[error] 	at __wrapper$1$a107ea65e29d4e0897dbed66118eca35.__wrapper$1$a107ea65e29d4e0897dbed66118eca35$.wrapper(<no source file>:25)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[error] 	at java.lang.reflect.Method.invoke(Method.java:597)
[error] 	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$compile$1.apply(ToolBoxFactory.scala:271)
[error] 	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:436)
[error] 	at scala.reflect.macros.runtime.Evals$class.eval(Evals.scala:16)
[error] 	at scala.reflect.macros.runtime.Context.eval(Context.scala:6)
[error] 	at remotely.GenServer$.impl(GenServer.scala:47)
[error] @GenServer(remotely.Protocol.empty.codec[Int].specify1("fac", Field.strict[Int]("in"), Type[Int]))
[error]  ^
[error] /Users/timperrett/sandbox/scala/ahjohannessen-remotely/examples/src/main/scala/Protocol.scala:30: exception during macro expansion:
[error] java.lang.NoClassDefFoundError: Could not initialize class remotely.Protocol$
[error] 	at __wrapper$1$1f0d05e367554422b5b1348a671df812.__wrapper$1$1f0d05e367554422b5b1348a671df812$.wrapper(<no source file>:30)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[error] 	at java.lang.reflect.Method.invoke(Method.java:597)
[error] 	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$compile$1.apply(ToolBoxFactory.scala:271)
[error] 	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:436)
[error] 	at scala.reflect.macros.runtime.Evals$class.eval(Evals.scala:16)
[error] 	at scala.reflect.macros.runtime.Context.eval(Context.scala:6)
[error] 	at remotely.GenClient$.impl(GenClient.scala:40)
[error] @GenClient(remotely.Protocol.empty.codec[Int].specify1[Int,Int]("fac", Field.strict[Int]("in"), Type[Int]).signatures)
[error]  ^
[error] /Users/timperrett/sandbox/scala/ahjohannessen-remotely/examples/src/main/scala/Protocol.scala:44: value environment is not a member of remotely.examples.FacServer{val fac: Int => remotely.Response[Int]}
[error]   lazy val env = facServer.environment
[error]                            ^
[error] three errors found
[info] Compiling 1 Scala source to /Users/timperrett/sandbox/scala/ahjohannessen-remotely/test/target/scala-2.10/classes...
[info] Compiling 12 Scala sources to /Users/timperrett/sandbox/scala/ahjohannessen-remotely/core/target/scala-2.10/test-classes...
[warn] /Users/timperrett/sandbox/scala/ahjohannessen-remotely/core/src/test/scala/SSLSpec.scala:213: discarded non-Unit value
[warn]       an[Exception] should be thrownBy fact.run
[warn]                                             ^

```

**Comment by ahjohannessen** [comment]
@timperrett that is really strange :/ What kind of JDK and OS do you have there? Compiles fine here for 2.10 and 2.11, I am on OS X Yosemite and have JDK8.

**Comment by ahjohannessen** [comment]
@timperrett could you try now to compile and run tests locally, that strange error should be gone now. I bumped to scodec 1.8.1 that depends on shapeless 2.2.4. Note, I have force pushed in order to get travis to build the PR, you probably need to delete the PR branch and fetch again if you have one still.

**Comment by ahjohannessen** [comment]
btw, Travis CI is a bit flaky.

**Comment by ahjohannessen** [comment]
ping @timperrett :)

**Comment by timperrett** [comment]
@ahjohannessen my bad, had an old JDK on the mac i used before.

**Comment by ahjohannessen** [comment]
@timperrett it would be nice with a new remotely release :)

**Comment by timperrett** [comment]
@ahjohannessen sure, i'll update the build and push one out

**Comment by timperrett** [comment]
@ahjohannessen so the project tests no longer pass for some reason? I cant look into it right now, but perhaps you have some cycles? The failing test is below - i've also updated the build to match our other projects in order to streamline the release process.

```
[info] ! Remote.roundtrip[Double]: Exception raised on property evaluation.
[info] > ARG_0: List()
[info] > ARG_1: Map()
[info] > Exception: java.lang.IllegalStateException: Pool not open
[info] + TupleCodec.tupele2Codec works: OK, passed 100 tests.
```

**Comment by ahjohannessen** [comment]
@timperrett That is odd, I do not get that specific error locally. This commit passes both on 2.10 and 2.11 for me, but current master code gives me some issues in tests with regards to an error being thrown. Not sure what is going on.

**Comment by ahjohannessen** [comment]
If I downgrade ScalaCheck back to 1.11.6 then current master passes all tests in 2.10 and 2.11 and no error is being thrown.

**Comment by timperrett** [comment]
@ahjohannessen its released :-) do note the change in group-id and artifact id:
`"oncue.remotely" %% "core" % "1.4.0"`

**Comment by ahjohannessen** [comment]
@timperrett super! :)

**Pull request merged**
