### PR TITLE
macros: add macros compatibility shims

### PR DESCRIPTION
**Pull request by ahjohannessen**
- add macros compatibility shims such that scala 2.10.x
   and scala 2.11.x code uses what is most appropriate.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
btw, the PR is not passing Travis CI, however not because of code in the PR, but rather due to SSL issues: https://travis-ci.org/oncue/remotely/jobs/51713516#L1097

**Comment by timperrett** [comment]
Need to look at this in more detail but it looks awesome!

**Comment by ahjohannessen** [comment]
Cool :)

**Comment by stew** [comment]
it looks good to me, I fixed the certs, which I'll checkin after the merge, but all the tests pass once the cert issues are gone.

**Pull request merged**
