### PR TITLE
bump core dependencies

### PR DESCRIPTION
**Pull request by larsrh**
Review by @timperrett.

### CODE REVIEW

**Comment by larsrh** [comment]
Not sure how the build for Scala 2.11 ever worked, but 2a7234a should fix that.

**Comment by timperrett** [comment]
@larsrh thanks for the PR! We'll need to support both 7.1 and 7.2 as we're still using 7.1 internally. We do this with knobs by separating the source dependencies that are version specific. WDYT?

**Comment by larsrh** [comment]
I'm afraid I don't yet follow – how do you do that?

**Comment by larsrh** [comment]
Wait, I might have misunderstood. The code cross-compiles against both versions fine; I don't think there's a need to separate sources.

**Comment by timperrett** [comment]
@larsrh ahh :) i meant that 7.1 and 7.2 are not 100% binary compatible, so i cant mix them on the classpath, right?

**Comment by larsrh** [comment]
Right. I don't think they are. But I guess a similar convention like `scodec` or `scalaz-stream` could work here; that is, putting an `a` suffix behind the `knobs` version. So there could be a `knobs-1.0a` and `knobs-1.0`. You can't use them at the same time but at least they're source-compatible.

**Comment by timperrett** [comment]
@larsrh right, and that is exactly what we do, but in order to do that the build needs work. If they are source compatible though that helps immensly. I'm just in the process of migrating the repos and builds over to the main verizon github (github.com/verizon) so I can probally take a stab at this today.

**Comment by larsrh** [comment]
Ah, I get it now. Cool, that would be much appreciated.

**Comment by larsrh** [comment]
*bump*

**Pull request closed without merging**
