### PR TITLE
Add some typelevel foo to Codecs! :-)

### PR DESCRIPTION
**Pull request by jedesah**
No more fast and loose with Protocol definitions!!

### CODE REVIEW

**Comment by timperrett** [comment]
@jedesah morning. Could you shed a little more light on this? Cheers

**Comment by stew** [comment]
@timperrett I think I can. what it does is makes the Protocol parameterized on the types for which it has codecs, then it makes sure that when you try to specify a remote method, it must be able to find evidence that a codec exists for all the parameter types and the return type of the method you are sepcifying

**Comment by jedesah** [comment]
@stew Glad you were able to figure that out! Hopefully that means my implementation was easy to understand :-)

I replied by email this morning, but for some reason it never showed up...

**Comment by jedesah** [comment]
Sorry. I guess my description is a little cryptic. :-)

This change makes it so one cannot declare a function over types not
included in the codecs of a protocol.

We briefly talked about this on Friday and since I was blocked on the other
PR, I figured I would try my hand at it and it was easier than I expected!

**Pull request merged**
